/**
 * Module identity colours, derived from the theme's palette.
 *
 * Every module family carries an identity colour — Transport amber, Note Order
 * pink, and so on — that paints its header stripe, its selection glow and its
 * cables. Those were hard-coded, so they ignored the theme entirely and a
 * fifty-theme roster would have had five colours punching through every one.
 *
 * Deriving them from the palette is what keeps a theme cohesive, but it has to
 * survive two things the palette cannot promise:
 *
 * 1. **A palette may not have five usable colours.** Some cards are two greys
 *    and a rust. Missing slots are generated by rotating around the palette's
 *    most chromatic hue rather than by inventing unrelated colours.
 * 2. **Two modules must never read as the same colour.** Palette hues are
 *    pushed apart to a minimum separation, because a Note Order and a Density
 *    that look identical is worse than a slightly inauthentic hue.
 *
 * Lightness and saturation are never taken from the palette — only hue is. The
 * same rule the token engine uses for surfaces applies here for the same
 * reason: it is what guarantees the accent is legible on this theme's
 * background instead of being whatever the card happened to contain.
 */

import { hexToRgb, hsl, rgbToHsl, type Tokens } from "../../lib/theme-studio";

/**
 * The identity slots, in assignment order. A palette's most chromatic colour
 * goes to the first, so the module a user looks at most keeps the palette's
 * strongest colour.
 */
export const MODULE_ACCENT_SLOTS = ["clock", "pattern", "order", "density", "midi", "audio"] as const;

export type ModuleAccentSlot = (typeof MODULE_ACCENT_SLOTS)[number];

export const moduleAccentToken = (slot: string): string => `--mm-module-${slot}`;

/**
 * Ink for text and icons sitting on top of an accent fill.
 *
 * The accent's own lightness is set by direction, not by the palette: a dark
 * theme's accents are light chips and a light theme's are dark ones. So the
 * contrasting ink is decided by direction too, and one value per theme is
 * enough — CSS cannot make this choice on its own without a class to branch on.
 */
export function accentInkToken(mode: "light" | "dark"): Tokens {
  return { "--mm-on-accent": mode === "dark" ? "#0b1016" : "#ffffff" };
}

/** Degrees two identity hues must differ by before they read as one colour. */
const MIN_SEPARATION = 26;

/** Where a generated hue goes when the palette runs out of chromatic colours. */
const FILL_OFFSETS = [48, -48, 96, -96, 144];

/** A colour with no chroma cannot carry identity; it would read as a grey chip. */
const CHROMATIC = 0.12;

type Pitch = { lightness: number; minSat: number; maxSat: number };

/**
 * Dark themes need a lighter, more saturated accent to lift off the surface;
 * light themes need a darker one to hold against a pale ground.
 */
const PITCH: Record<"light" | "dark", Pitch> = {
  dark: { lightness: 0.63, minSat: 0.45, maxSat: 0.82 },
  light: { lightness: 0.44, minSat: 0.48, maxSat: 0.88 },
};

const clamp = (value: number, low: number, high: number): number =>
  Math.min(high, Math.max(low, value));

/**
 * Push hues apart until no two are closer than `MIN_SEPARATION`.
 *
 * Separation has to be judged around the wheel, not along the array: the hues
 * arrive ordered by saturation, so the two that collide are frequently not
 * neighbours in the list. A palette of three browns and a blue would otherwise
 * pass a neighbour-only check while still painting three modules the same
 * colour.
 *
 * So the ring is sorted, spread forward from its first member, and mapped back
 * to the original slots. The palette's strongest colour anchors the ring and
 * keeps its own hue; the compromise lands on the rest.
 */
function separate(hues: number[]): number[] {
  const count = hues.length;
  // Both guards are unreachable from the one caller, which always asks for
  // exactly `MODULE_ACCENT_SLOTS.length` hues. They stay because this is a
  // general spread over a ring and the next caller may not be so tidy.
  /* v8 ignore next */
  if (count < 2) return [...hues];

  // Sorting by hue but remembering where each came from is what lets the
  // spread be correct and the slot assignment stay stable.
  const ring = hues
    .map((hue, index) => ({ hue: ((hue % 360) + 360) % 360, index }))
    .sort((a, b) => a.hue - b.hue);

  // Five slots at 26° need 104° of the wheel, so an even spread is always
  // available as a fallback and never has to crowd anything.
  /* v8 ignore next */
  if (count * MIN_SEPARATION > 360) return hues.map((_, i) => (hues[0] + (360 / count) * i) % 360);

  const anchor = ring[0].hue;
  for (let i = 1; i < count; i++) {
    const previous = ring[i - 1].hue;
    if (ring[i].hue - previous < MIN_SEPARATION) ring[i].hue = previous + MIN_SEPARATION;
  }
  // Closing the ring: the gap from the last back round to the first counts too.
  if (anchor + 360 - ring[count - 1].hue < MIN_SEPARATION) {
    for (let i = 0; i < count; i++) ring[i].hue = anchor + (360 / count) * i;
  }

  const out = new Array<number>(count);
  for (const entry of ring) out[entry.index] = ((entry.hue % 360) + 360) % 360;
  return out;
}

/**
 * Five identity hues for a palette: its own chromatic colours first, most
 * saturated first, then generated fills around the strongest hue.
 */
export function moduleAccentHues(colors: readonly string[]): number[] {
  const parsed = colors
    .map((hex) => rgbToHsl(hexToRgb(hex)))
    .filter((color) => Number.isFinite(color.h));
  const chromatic = parsed.filter((color) => color.s >= CHROMATIC).sort((a, b) => b.s - a.s);

  // A palette of pure greys still has to produce five distinguishable chips, so
  // fall back to a neutral base hue and let the fills do all the work.
  const base = chromatic[0]?.h ?? parsed.sort((a, b) => b.s - a.s)[0]?.h ?? 210;

  const hues = chromatic.slice(0, MODULE_ACCENT_SLOTS.length).map((color) => color.h);
  for (let i = 0; hues.length < MODULE_ACCENT_SLOTS.length; i++) {
    hues.push((base + FILL_OFFSETS[i % FILL_OFFSETS.length] + 360) % 360);
  }
  return separate(hues);
}

/**
 * The identity tokens for one theme.
 *
 * `saturations` follows the same order as the hues so a muted palette stays
 * muted, clamped into a band that keeps every chip readable as a colour.
 */
export function deriveModuleAccents(
  colors: readonly string[],
  mode: "light" | "dark",
): Tokens {
  const pitch = PITCH[mode];
  const hues = moduleAccentHues(colors);
  const saturations = colors
    .map((hex) => rgbToHsl(hexToRgb(hex)))
    .filter((color) => color.s >= CHROMATIC)
    .sort((a, b) => b.s - a.s)
    .map((color) => color.s);

  const tokens: Tokens = { ...accentInkToken(mode) };
  MODULE_ACCENT_SLOTS.forEach((slot, index) => {
    const saturation = clamp(saturations[index] ?? saturations[0] ?? 0.6, pitch.minSat, pitch.maxSat);
    tokens[moduleAccentToken(slot)] = hsl(hues[index], saturation, pitch.lightness);
  });
  return tokens;
}

/**
 * The hand-authored identity colours, used by the themes that have no palette
 * to derive from. These are Modular's original five.
 */
export function fixedModuleAccents(mode: "light" | "dark"): Tokens {
  const source: Record<ModuleAccentSlot, string> = {
    clock: "#ffb703",
    pattern: "#4cc9f0",
    order: "#f15bb5",
    density: "#00d4a6",
    midi: "#9b5de5",
    audio: "#ff6b4a",
  };
  const pitch = PITCH[mode];
  const tokens: Tokens = { ...accentInkToken(mode) };
  for (const slot of MODULE_ACCENT_SLOTS) {
    const color = rgbToHsl(hexToRgb(source[slot]));
    tokens[moduleAccentToken(slot)] = hsl(
      color.h,
      clamp(color.s, pitch.minSat, pitch.maxSat),
      // Light themes darken the originals so they hold against a pale canvas;
      // dark themes keep them close to where they were designed.
      mode === "dark" ? clamp(color.l, 0.5, 0.68) : pitch.lightness,
    );
  }
  return tokens;
}
